template:
  path: transit-gateway-peering.yaml
parameters:
  TransitGatewayId: !stack_output transit-gateway-peering-minimal/eu-west-1/transit-gateway.yaml::TransitGatewayId
  PeerTransitGatewayId: !stack_output transit-gateway-peering-minimal/eu-central-1/transit-gateway.yaml::TransitGatewayId
  PeerRegion: !stack_output transit-gateway-peering-minimal/eu-central-1/transit-gateway.yaml::Region
