template:
  path: vpc-ec2.yaml
depends_on: ["transit-gateway-peering-full/eu-west-1/transit-gateway.yaml"]
parameters:
  CidrBlock: "10.0.0.0/16"
  SubnetCidrBlock: "10.0.1.0/24"
  KeyName: "awsBinx"
