AWSTemplateFormatVersion: "2010-09-09"
Description: "TGW"
Resources:
  TransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      Description: "TGW"
      AutoAcceptSharedAttachments: "disable"
      DefaultRouteTableAssociation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
        - Key: "Name"
          Value: "TransitGateway"

Outputs:
  TransitGatewayId:
    Value: !GetAtt TransitGateway.Id
  Region:
    Value: !Ref AWS::Region
