AWSTemplateFormatVersion: "2010-09-09"
Description: "TGW"
Parameters:
  SubnetId:
    Type: String
  VpcId:
    Type: String
  TransitGatewayId:
    Type: String
  VpcRouteTable:
    Type: String
  TGWDestinationCidrBlock:
    Type: String
  TransitGatewayPeeringAttachmentId:
    Type: String

Resources:
  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      SubnetIds:
        - !Ref SubnetId
      TransitGatewayId: !Ref TransitGatewayId
      VpcId: !Ref VpcId
      Tags:
        - Key: "Name"
          Value: "TransitGatewayPeeringDemo"

  TransitGatewayRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  TransitGatewayPeeringRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayPeeringAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  TransitGatewayRouteTablePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  TransitGatewayRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGatewayId
      Tags:
        - Key: "Name"
          Value: "TransitGatewayPeeringDemo"

  TransitGatewayRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      DestinationCidrBlock: !Ref TGWDestinationCidrBlock
      TransitGatewayAttachmentId: !Ref TransitGatewayPeeringAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  TransitGatewayVpcRoute:
    Type: AWS::EC2::Route
    DependsOn: TransitGatewayAttachment
    Properties:
      RouteTableId: !Ref VpcRouteTable
      DestinationCidrBlock: !Ref TGWDestinationCidrBlock
      TransitGatewayId: !Ref TransitGatewayId
